[workspace]
members = [
  "eventshop-messaging-core",
  "eventshop-messaging-rabbitmq"
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1"
futures-util = "0.3"
lapin = "2"
metrics = "0.23"
metrics-exporter-prometheus = "0.15"
dashmap = "6"
tokio-util = { version = "0.7", features = ["rt"] }
